name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Configuration
        env:
          OPENAI_API_KEY_VAL: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN_VAL: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: | 
          export OPENAI_API_KEY="OPENAI_API_KEY_VAL"
          export TELEGRAM_BOT_TOKEN="TELEGRAM_BOT_TOKEN_VAL"
          echo $OPENAI_API_KEY
          echo $TELEGRAM_BOT_TOKEN
          echo "done..."
          ls -l
          pip3 install -r requirements.txt
          python bot.py